### ISSUE TITLE
Main context is None when it should be default

### ISSUE THREAD

**Issue by jbarry-bdai** [bdaiinstitute/ros_utilities#66]
Running the `background_action_example.py` I get an error about the main context being `None`:

```
jbarry@bdai_docker:/workspaces/bdai/ws/src/external/ros_utilities/bdai_ros2_wrappers/examples$ python background_action_example.py 
Traceback (most recent call last):
  File "/workspaces/bdai/ws/src/external/ros_utilities/bdai_ros2_wrappers/examples/background_action_example.py", line 84, in <module>
    main()
  File "/workspaces/bdai/_build/build/bdai_ros2_wrappers/bdai_ros2_wrappers/process.py", line 176, in __call__
    return func_taking_no_args()
  File "/workspaces/bdai/ws/src/external/ros_utilities/bdai_ros2_wrappers/examples/background_action_example.py", line 69, in main
    while main.context.ok():
AttributeError: 'NoneType' object has no attribute 'ok'
```

**Comment by mhidalgo-bdai** [comment]
As per offline discussion, the issue is that `ROSAwareScope.context` is in fact `None`. For the underlying ROS 2 APIs, that is code for using the (global) default context. It is important that the scope instance retains that `None` value to survive (global) default context re-initializations, but the property should not yield `None` but the corresponding context object.
