### ISSUE TITLE
warnings during build

### ISSUE THREAD

**Issue by dan9thsense** [bdaiinstitute/ros_utilities#77]
Ran into these during build; thought you would want to know.

```
Starting >>> proto2ros_tests
--- stderr: proto2ros_tests                                 
/home/dbarry/ariac_ws/install/proto2ros/lib/python3.10/site-packages/proto2ros/dependencies.py:45: UserWarning: Dependency cycle found: proto2ros_tests/Fragment -> proto2ros_tests/Fragment
  warnings.warn("Dependency cycle found: " + dependency_cycle_depiction, stacklevel=1)
/home/dbarry/ariac_ws/install/proto2ros/lib/python3.10/site-packages/proto2ros/dependencies.py:58: UserWarning: Type erasing nested member in proto2ros_tests/Fragment to break recursion
  warnings.warn(f"Type erasing {field.name} member in {message_type} to break recursion", stacklevel=1)
/home/dbarry/ariac_ws/install/proto2ros/lib/python3.10/site-packages/proto2ros/dependencies.py:45: UserWarning: Dependency cycle found: proto2ros_tests/Value -> proto2ros_tests/ValueOneOfData -> proto2ros_tests/Pair -> proto2ros_tests/Value
  warnings.warn("Dependency cycle found: " + dependency_cycle_depiction, stacklevel=1)
/home/dbarry/ariac_ws/install/proto2ros/lib/python3.10/site-packages/proto2ros/dependencies.py:58: UserWarning: Type erasing pair member in proto2ros_tests/ValueOneOfData to break recursion
  warnings.warn(f"Type erasing {field.name} member in {message_type} to break recursion", stacklevel=1)
---
Finished <<< proto2ros_tests [9.34s]
```

**Comment by dan9thsense** [comment]
On a different machine it generates this error:

```
Starting >>> proto2ros_tests
--- stderr: proto2ros_tests                               
FileNotFoundError in template '/opt/ros/iron/share/rosidl_generator_c/cmake/../resource/full__description.c.em': [Errno 2] No such file or directory: '/home/dbarry/ariac_ws/build/proto2ros_tests/proto2ros_generate/proto2ros_tests/msg/Direction.msg'
FileNotFoundError when expanding 'idl__description.c.em' into '/home/dbarry/ariac_ws/build/proto2ros_tests/rosidl_generator_c/proto2ros_tests/msg/detail/direction__description.c': [Errno 2] No such file or directory: '/home/dbarry/ariac_ws/build/proto2ros_tests/proto2ros_generate/proto2ros_tests/msg/Direction.msg'
Error processing idl file: /home/dbarry/ariac_ws/build/proto2ros_tests/rosidl_adapter/proto2ros_tests/msg/Direction.idl
Traceback (most recent call last):
  File "/opt/ros/iron/share/rosidl_generator_c/cmake/../../../lib/rosidl_generator_c/rosidl_generator_c", line 42, in <module>
    sys.exit(main())
  File "/opt/ros/iron/share/rosidl_generator_c/cmake/../../../lib/rosidl_generator_c/rosidl_generator_c", line 38, in main
    generate_c(args.generator_arguments_file, args.disable_description_codegen)
  File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_generator_c/__init__.py", line 41, in generate_c
    return generate_files(
  File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_pycommon/__init__.py", line 116, in generate_files
    raise(e)
  File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_pycommon/__init__.py", line 107, in generate_files
    expand_template(
  File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_pycommon/__init__.py", line 169, in expand_template
    interpreter.string(template_content, template_path, locals=data)
  File "/usr/lib/python3/dist-packages/em.py", line 2391, in string
    self.safe(scanner, True, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1531, in run
    self.subrun(elseTokens, interpreter, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1631, in subrun
    token.run(interpreter, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2596, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 2, in <module>
  File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_pycommon/__init__.py", line 218, in _expand_template
    interpreter.string(content, str(template_path), kwargs)
  File "/usr/lib/python3/dist-packages/em.py", line 2391, in string
    self.safe(scanner, True, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2596, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 49, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/dbarry/ariac_ws/build/proto2ros_tests/proto2ros_generate/proto2ros_tests/msg/Direction.msg'
Exception ignored in: <function Interpreter.__del__ at 0x7ae2b912a710>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/em.py", line 2094, in __del__
  File "/usr/lib/python3/dist-packages/em.py", line 2157, in shutdown
  File "/usr/lib/python3/dist-packages/em.py", line 2647, in finalize
  File "/usr/lib/python3/dist-packages/em.py", line 2200, in push
AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
gmake[2]: *** [CMakeFiles/proto2ros_tests__rosidl_generator_c.dir/build.make:188: rosidl_generator_c/proto2ros_tests/msg/direction.h] Error 1
gmake[2]: *** Deleting file 'rosidl_generator_c/proto2ros_tests/msg/direction.h'
gmake[1]: *** [CMakeFiles/Makefile2:285: CMakeFiles/proto2ros_tests__rosidl_generator_c.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/home/dbarry/ariac_ws/install/proto2ros/lib/python3.10/site-packages/proto2ros/dependencies.py:49: UserWarning: Dependency cycle found: proto2ros_tests/Fragment -> proto2ros_tests/Fragment
  warnings.warn("Dependency cycle found: " + dependency_cycle_depiction)
/home/dbarry/ariac_ws/install/proto2ros/lib/python3.10/site-packages/proto2ros/dependencies.py:62: UserWarning: Type erasing nested member in proto2ros_tests/Fragment to break recursion
  warnings.warn(f"Type erasing {field.name} member in {message_type} to break recursion")
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< proto2ros_tests [6.79s, exited with code 2]

Summary: 20 packages finished [48.2s]
  1 package failed: proto2ros_tests
  1 package had stderr output: proto2ros_tests
```

**Comment by jbarry-bdai** [comment]
@mhidalgo-bdai any ideas?  is this an iron/humble mismatch?

@dan9thsense what build command are you running?  if you're only depending on `bdai_ros2_wrappers` can you avoid building the `proto2ros` stuff?  it's a different package.  i would also suggest cleaning your build and trying again.

**Comment by dan9thsense** [comment]
bdai_ros2_wrappers builds fine and I can avoid the protoros2 stuff.  I just thought you would want to know.

**Comment by dan9thsense** [comment]
Oh, and deleting build and trying causes the overall workspace build to fail. I have to remove ros_utilities from the folder, build the workspace, bring ros_utilities back, and then do a build selecting only the bdai_ros2_wrappers package.  It's a kludge.

**Comment by dan9thsense** [comment]
Unfortunately, I'm now getting protobuf errors during sim runs:

[gzserver-1] [libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:1694] CHECK failed: (index) < (current_size_): 
[gzserver-1] terminate called after throwing an instance of 'google::protobuf::FatalException'

**Comment by mhidalgo-bdai** [comment]
There are many different things at play here. I would suggest separate tickets moving forward.

> warnings during build

These are expected. It's `proto2ros` visibly warning the user (you) that it had to deal with a recursive data structure by "type erasing" a field in the corresponding circular dependency cycle, which will affect how you make use of the generated messages (most fields will be typed just fine, as documented in the wiki, but these won't).

> On a different machine it generates this error:
> @mhidalgo-bdai any ideas? is this an iron/humble mismatch?

These are errors deep down `rosidl`, within [`empy`](https://pypi.org/project/empy/) specifically. I would suspect a version mismatch somewhere, but I could be wrong. We would have to dig deeper. That said, this definitely does not look like a `proto2ros` issue.

> Oh, and deleting build and trying causes the overall workspace build to fail. I have to remove ros_utilities from the folder, build the workspace, bring ros_utilities back, and then do a build selecting only the bdai_ros2_wrappers package. It's a kludge.

This seems unusual. I would suspect user error. These packages were developed and tested against Humble. Consider doing a clean build using `colcon` against a local Humble installation.

> Unfortunately, I'm now getting protobuf errors during sim runs:

That is yet another, different problem. I would suspect a mismatch in Protobuf versions. Gazebo may be relying on some Protobuf version that is incompatible with the one that `rosdep` pulls in (as it is listed as a `proto2ros` dependency). We would have to dig deeper. 

Short term, if you don't need `proto2ros`, skip it entirely. You can do a [sparse checkout](https://medium.com/@judyess/how-to-clone-specific-subdirectory-branch-with-git-3fb02fd35b68) if that helps. Eventually, `proto2ros` could be moved to its own repository, separate from wrappers.
